[package]

name = "showfs"
version = "0.0.1"
authors = ["toshipp <toshiq2@gmail.com>"]

[dependencies]
libarchive = "*"
libarchive3-sys = "*"
time = "*"
fuse = "*"
libc = "*"
log = "0.3.5"
env_logger = "0.3.5"
