version: 2
jobs:
  test:
    docker:
      - image: rust
    steps:
      - checkout
      - run: |
          apt-get update
          apt-get install -y build-essential pkg-config libfuse-dev libarchive-dev python3
      - run: |
          cargo install cargo-audit
          cargo audit -D
      - run: |
          ./tool/make_assets.py
          cargo test --all

workflows:
  version: 2
  ci:
    jobs:
      - test
